### ISSUE TITLE
Not working with Grafana 7.0

### ISSUE THREAD

**Issue by nthienan** [michaeldmoore/michaeldmoore-annunciator-panel#8]
The panel does not show the value when upgrading Grafana to version 7.0

**Comment by michaeldmoore** [comment]
Are you running the latest version - v1.0.5 released April 12th?  This version has specific modifications for the updated DOM model presented by Grafana 6.7.0+ and 7.0

**Comment by nthienan** [comment]
oh, I'm using 1.0.2. Let me upgrade to v1.0.5

**Comment by nthienan** [comment]
I'm going to close this since v1.0.5 works as expected. Thanks @michaeldmoore
